### ISSUE TITLE
ST_Union(ST_Intersection) return null in specific cases of clusters

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-knownprojects#352] opened 2021-07-14 17:19 UTC
Hi @SPTKL @mgraber ! Just want to make this an issue to better facilitate working on this. The content below is the same as in the HED question thread.

 After getting all the intermediate tables from clustering, I was able to narrow the issue to the this query in the clustering step. 

https://github.com/NYCPlanning/db-knownprojects/blob/57ff42d33bea4d2d579970a191345a265c95fc05/sql/_project_record_ids.sql#L36-L45

For one instance, P2018R0253 and 2019R0295, the two records are correctly identified by the dbscan step that they are clusters and still joined together in the project_record_join step. But then the all_intersections do not return any geometry for this cluster and they are consequently broken up in the last step by the [ST_overlap statement](https://github.com/NYCPlanning/db-knownprojects/blob/57ff42d33bea4d2d579970a191345a265c95fc05/sql/_project_record_ids.sql#L50). I am not quite sure what exactly why but my guess now is in cases where one geometry is completely within another the [ST_Intersection](https://postgis.net/docs/ST_Intersection.html) does not behave as we expect.  Please take a look at [this batch output](https://github.com/NYCPlanning/db-knownprojects-data/tree/output-20210712-2010/output/review) with all the intermediate tables for more details. I am thinking about the solutions for this. Please let me know if you have any suggestions! Thank you very much!

**Comment by td928** [comment] 2021-07-14 17:24
bc19fb7 use a different function than ST_UNION() to get the collection of intersections. Function failed due to inconsistent geometry type.

**Comment by td928** [comment] 2022-10-21 20:17
After digging through some of the history for this script, it was found that this logics were added when trying to address the issue with [clusters where only boundaries are touching](https://github.com/NYCPlanning/db-knownprojects/issues/307). This solution from Molly quite elegantly solve for many of those cases but fail to address the edge cases where the clusters are two polygon where one completely contains the other. Then `ST_INTERSECT` will return null. Then, in those situations, the clusters will be broken up.

**Comment by AmandaDoyle** [comment] 2022-11-14 18:16
@td928 I do not think the issue is with the `ST_INTERSECTION` statement.  Also, note that there is a difference between 
`ST_INTERSECTION` and `ST_INTERSECTS`.  

It's my understanding that in [db-knownprojects/sql/_project_record_ids.sql](https://github.com/NYCPlanning/db-knownprojects/blob/57ff42d33bea4d2d579970a191345a265c95fc05/sql/_project_record_ids.sql#L36-L45) the following is happening.
1) a cluster ID is assigned to each record https://postgis.net/docs/ST_ClusterDBSCAN.html
2) the number of records is calculated in each cluster
3) The spatial intersection of all geometries is calculated and outputted
4) Cluster are finalized.  I think it's the `ST_OVERLAPS` function that may be dropping the records you're looking to retain.  Should this be changed to `ST_INTERSECTS` or add another clause i.e.
'''
WHERE (ST_OVERLAPS(a.geom, b.intersect_geom) OR ST_Within(a.geom, b.intersect_geom))
AND a.id IS NOT NULL
'''
See guide here for spatial functions: http://postgis.net/workshops/postgis-intro/spatial_relationships.html

Happy to talk this through and work together get desired output.

**Comment by td928** [comment] 2022-11-14 18:35
> @td928 I do not think the issue is with the `ST_INTERSECTION` statement. Also, note that there is a difference between `ST_INTERSECTION` and `ST_INTERSECTS`.
> 
> It's my understanding that in [db-knownprojects/sql/_project_record_ids.sql](https://github.com/NYCPlanning/db-knownprojects/blob/57ff42d33bea4d2d579970a191345a265c95fc05/sql/_project_record_ids.sql#L36-L45) the following is happening.
> 
> 1. a cluster ID is assigned to each record https://postgis.net/docs/ST_ClusterDBSCAN.html
> 2. the number of records is calculated in each cluster
> 3. The spatial intersection of all geometries is calculated and outputted
> 4. Cluster are finalized.  I think it's the `ST_OVERLAPS` function that may be dropping the records you're looking to retain.  Should this be changed to `ST_INTERSECTS` or add another clause i.e.
>    '''
>    WHERE (ST_OVERLAPS(a.geom, b.intersect_geom) OR ST_Within(a.geom, b.intersect_geom))
>    AND a.id IS NOT NULL
>    '''
>    See guide here for spatial functions: http://postgis.net/workshops/postgis-intro/spatial_relationships.html
> 
> Happy to talk this through and work together get desired output.

yeah it is not the intersects itself is an issue but when `ST_OVERLAPS` is run on null geometry is then causing the issue. 

I think the issue with your solution might be that if `b.intersect_geom ` is null then `ST_Within` will still return `False` and clusters would get dropped.

**Closed** 2022-12-02 18:05 UTC
Labels: bug
